### ISSUE TITLE
Getting Minecraft and Liteloader to work in 1.7.10

### ISSUE THREAD

**Issue by Ultrasonic54321** [MultiMC/Launcher#527]
Guys, i have went into a problem with Minecraft. When i installed Minecraft Forge and Liteloader, i ended up with this:

```
21:40:15] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiOpenEvent
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiOpenEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.9.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.tree.MethodInsnNode.<init>(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
    at cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:144) ~[forge-1.7.10-10.13.1.1219.jar:?]
    at cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:63) ~[forge-1.7.10-10.13.1.1219.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276) ~[launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174) ~[launchwrapper-1.9.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
```

Can anyone help me? 
Thanks.
